### ISSUE TITLE
Blueskyが落ちてるときの対処

### ISSUE THREAD

**Issue by ryotn** [ryotn/concrnt2SNS#12]
Blueskyが落ちてるとコイツも落ちるのでいい感じにtry...catchしようね
```
Error: TypeError: fetch failed
    at AtpAgent.defaultFetchHandler [as fetch] (/home/ryotn/concrnt2SNS/node_modules/@atproto/xrpc/dist/client.js:135:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BskyAgent._fetch (/home/ryotn/concrnt2SNS/node_modules/@atproto/api/dist/agent.js:330:19)
    at async ServiceClient.call (/home/ryotn/concrnt2SNS/node_modules/@atproto/xrpc/dist/client.js:88:21)
    at async PostRecord.create (/home/ryotn/concrnt2SNS/node_modules/@atproto/api/dist/client/index.js:1644:21)
    at async AtProtocol.post (/home/ryotn/concrnt2SNS/AtProtocol.js:52:9)
```

```
Error: Not Enough Resources
    at ServiceClient.call (/home/ryotn/concrnt2SNS/node_modules/@atproto/xrpc/dist/client.js:109:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostRecord.create (/home/ryotn/concrnt2SNS/node_modules/@atproto/api/dist/client/index.js:1644:21)
    at async AtProtocol.post (/home/ryotn/concrnt2SNS/AtProtocol.js:52:9)
```

**Comment by ryotn** [comment]
AtProtocol全体的にちゃんとしたい。
